export const path = {
  home: "/",
  cocoon: "/cocoon",
  coreValue: "/cocoon/gia-tri-cot-loi",
  storyBrand: "/cocoon/cau-chuyen-thuong-hieu",
  communityResponsibility: "/cocoon/trach-nhiem-cong-dong",
  cart: "/cocoon/cart",
  search: "/cocoon/search",
  article: "/cocoon/bai-viet",
  beauty: "/cocoon/bai-viet/lam-dep",
  charity: "/cocoon/bai-viet/chuong-trinh",
  promotion: "/cocoon/khuyen-mai",
  product: "/cocoon/san-pham",
  productInfo: "/cocoon/san-pham/:id",
  contact: "/cocoon/contact",
  checkout: '/cocoon/checkout',
  post1: "/cocoon/bai-viet/post1",
  post2: "/cocoon/bai-viet/post2",
  post3: "/cocoon/bai-viet/post3",
  post4: "/cocoon/bai-viet/post4",
  post5: "/cocoon/bai-viet/post5",
  post6: "/cocoon/bai-viet/post6",
};
